### PR TITLE
Further build modifications

### PR DESCRIPTION
**Pull request by fer-rum**
As discussed on [the recent split commit](https://github.com/livecv/livecv/commit/a3cf595a6c32badd631aa394d8eb898e76177ee7), there are still some build issues to be handled.

This pull request incorporates the upstream changes @dinusv made in the meantime and offers fixes on the *rpath* issue, plugin inclusion and an option to enable config files in the qtcreator file tree.

The runtime inclusion of QML plugins does currently not work (again :sob: )  and will **not** be handled by this pull request. (It will be either resolved upstream or in a separate pull request.)

### CODE REVIEW

**Comment by dinusv** [comment]
Interesting, I'll have a look on that, most probably by tomorrow. Also, you have 2 ```linkLocalPlugins``` functions, in one of them, ```live``` library is treated separately. Are you sure you are getting the right function called?

**Comment by fer-rum** [comment]
There should be a `linklocalLibrary` and a `linklocalPlugin` The latter is a variation of the former and accomodates for the deployment differences between libraries (like *editor*) and plugins (like *live*) . I didn't notice a duplicate of `linklocalPlugin` in the diff, but will double-check the code. 
Also, I should probably insert a few explainatory lines of comment...

**Comment by fer-rum** [comment]
Ah, I see what happened here. One version of `linklocalPlugin` is the one I wrote and the other one is the one you wrote. In your version `liblive.so` (/.dll/.dylib) is deployed directly to the application dir, like a library, in my version it is deployed to its own plugin subdirectory (like a plugin).
The latter approach of course requires the involved plugin dirs to be a part of the *rpath* and the loading mechanism to be aware in which directory to look.
Another option would be to merge *live* into the core application, if it is vital to the execution of the application.

What would be the pros/cons of making *live* 
* a library (like it originally was)?
* a plugin (like it currently is)?
* a part of the core application?

Whatever the decision is, it would be desirable to treat all plugins the same and all libraries the same. Exceptions only create confusion. A plugin that always gets loaded since everything depends on it, in my book would not be a plugin but a part of the core application. (And nothing speaks against making it a library and add the involved QML resources to the binary or - even better - just deploy the QML into a application wide *qml* directory, instead of using the qrc for that.)

**Comment by fer-rum** [comment]
I noticed that the third option would make it hard to actually link plugins, so that option is likely a no-go.

**Comment by fer-rum** [comment]
Question about your Windows build: How are your local build profiles set up?

By default, qtcreator uses different root build directories for *debug*, *release*, *profile* etc.
This should reflect in the `shadow()`-qmake function. and from there on, no further distinction regarding to the build mode would be required. (Which means, we do actually not need any specific handling further down the build tree, making the whole configuration a lot less easier.)

What I would expect, that the build dir is configured as something like `.../livecv/build/<build-mode>` in the project configuration, not just `.../livecv/build`. 

If the latter would be the case, that would indeed explain why you always try/have to manually configure build paths with respect to the current build mode, even though your tools can easily handle that for you. 

I added a screenshot of my debug configuration for comparison/clarification:

buildconfig_livecv

**Comment by dinusv** [comment]
Plugin inclusion should work now, the qmldir's weren't deployed properly apparently.

Regarding **live library** : It's both, 

 * I need to link from it from the application to initialize values used by other plugins (like arguments, staticloaders, licenses, palettes), therefore it needs to reside in the application dir
 * and it's a plugin since it's types need to be registered to qml. 

To fix this the only solution would be to break it into 2 separate libraries: a main one which live cv and other plugins can link to, and one used for imports(which also links to the main one) to register the types. I think for now it would complicate things, and I'm not sure future libraries like this would exist (then I would have to split all of them). I have to think about it a bit until I do the actual split, maybe in the next version.

Regarding **QtCreator**:

On both OS's I leave it on as default, so it's src/../build<build_mode>, but the problem is when using qmake separately it doesn't do that for you

**Comment by fer-rum** [comment]
Regarding ***live***: A library should be perfectly able to register types for qml as well shouldn't it?

Regarding **qmake**: I see where the trouble comes from. But on the one hand: 
> Why would you call qmake manually unless in a script

and on the other: 
> Naturally you then have to provide all the required options to facilitate a proper build.

What is the intended purpose of throwing all possible configuration details of all supported OS's in there? These all are completely user-local settings that have IMHO no place in the generic build process.
If one needs a simple "out-of-the-box" solution, one usually provides pre-built binaries and an installer.

**Comment by dinusv** [comment]
Regarding **live**: Yes, by specifying it in a qmldir file that's placed in a locatable directory :) Otherwise you miss out on the separate qml files.
Regarding **qmake**: Mostly scripts, but some ppl use different editors, so then you have to account for those (there's plugins for those that prefer default behavior). I'm not sure why Qt choose this way, especially since its only specific to windows to have debug and release inside a build, I haven't managed to find out the reason, so if I'm not sure, I find it safer to stick with default behavior. Maybe it's cause of the ```CONFIG += build_all``` flag, which lets you build both, but then why doesn't it do the same on linux systems?

**Comment by fer-rum** [comment]
Usually you want to separate *debug*, *release*, *profile*, ... builds since they may behave different and generate different code. (E.g. when using assertions as you should.) Also a *release* build usually will not contain any debug symbols in the binary. I have the builds split under Linux too.
However the splitting should be done as early in the build path as possible (In the example I posted above it is done directly before the build path root, after the compiler setup distinction).

Also mixing them might lead the *make* process astray and it might not re-compile parts of the application even if it should because you changed the build configuration.

Under Windows afaik, debug symbols are not included in the *.dll* but in a separate lookup file, which makes a _debug_ build even more different from a _release_ one.

**Regarding the usage of *qmake* in other setups:** While the QtCreator sets up all the options for you, (the default setting provides some options to *qmake*), other tools arguably might not. There it would be the tool-user's responsibility to set it up correctly. The easiest way would be to proclaim the options, the QtCreator would usually insert. I am currently not aware of any people developing Qt with third party tools and might dare to say that they are a very small minority. (Biased opinion of course.) Considering the effort-gain relationship, we might want to go for a build that is easy to maintain with the *QtCreator* so we can move on and add build support for other tools, once there is a demand (is there some at the moment?) and we have someone using a different tool that can confirm whether it works.

**Comment by fer-rum** [comment]
There is one thing that still eludes me: the combination of 
* the placement of *qmldir*
* the name of the module it describes
* the QML Import path

According to [the Qt documentation](https://doc.qt.io/qt-5/qtqml-modules-identifiedmodules.html) (and clarified in [this stackoverflow post)](http://stackoverflow.com/questions/35352930/qt5-qml-module-is-not-installed#35358785) the setup should look something like this:
*Folder structure:*
```
…/plugins/live
    |- liblive.so
    |- qmldir
    |- qml
        |- … .qml
```
*qmldir:*
``` 
module live
plugin live

Foo  1.0 qml/Foo.qml
```

And the *QmlImportPath* has to point to the directory in which the module resides (Did I get that right?), which would be the *plugins* folder.

What I don't get is how it should work if one were to place the *qmldir* file directly in the *qml* folder. (These setups never worked for me.) 

@dinusv how is it on your end, does this actually work as it currently is? Is there any specific reason, why the *qmldir* file should be in the *qml* folder?

**Comment by fer-rum** [comment]
I changed the *qmldir* in the way described above. This seems to be the configuration that works best on my setup. Before pulling, can you please checkout this branch, build and run it and see if the importing plugins works for you? If not, please tell me what goes wrong and I will try to fix these issues.

However, I will use this point as the base for further work (aka. the stuff I originally intended to do two weeks ago.) I took the liberty of tagging it as `linux_build_config` for later reference.

For future coordination, is there any preferred way I can contact you, so we do not have to discuss everything in some commit message?

**Comment by dinusv** [comment]
**Regarding debug/release/profile**: Yea, it makes sense, I did some searching and still haven't found out why qmake doesn't rewrite the debug/release behavior by default, but there's nothing really for it, so let's rewrite it.

**Regarding qmldir**: I see now why this created confusion, commit c85bceb is actually key here, which solves the qmldir deployment issue.

This is the deploy structure I'm looking for, which is standard:
```
…/plugins/live
    |- liblive.so
    |- qmldir
    |- *.qml
```

The deploy structure you probably got:

```
…/plugins/live
    |- liblive.so
    |- qml
        |- qmldir
        |- *.qml
```

Only the contents of the ```qml``` folder is actually meant to be copied, I actually missed the fact that the two OSes handle the copying differently.

And yes, the ```qmlimportpath``` needs to point to the ```plugins``` folder, but I assume this all makes sense now.

I have to wrap something up, I will do the commit after and it should work then.

**Regarding contact**: Of course, send me your email here http://dinusv.com/contact

**Comment by fer-rum** [comment]
> Only the contents of the qml folder is actually meant to be copied,

Now I get it. *< Sudden enlightenment occurs >* 
So… this branch currently uses a separate QML folder (which cleans stuff up a bit, especially when you add additional resources) but I can switch to the behaviour you intent, which would help keeping the branches in sync (and probably make the build process a bit easier and more bulletproof).

Will do the latter, we can go back to the *dedicated QML directory* version if required (and we can look up how it works in the commit history).

**Comment by dinusv** [comment]
So I've managed to remove live library from the application, but I've currently disabled 2 components (one of them is part of ```live/mainscript.qml``` sample. I will have to see how I find alternatives to bring them back.

I've moved the rest of dependencies to lcveditor lib, since palettes are in a way part of the editor, so they make sense there.

The ```import live 1.0``` statement is now important, since it triggers the ```StaticContainer``` object to be created before loading any projects, since some projects tend to use it.

**Pull request merged**
