### PR TITLE
New plugin: lcvphoto

### PR DESCRIPTION
**Pull request by tvdstaaij**
This is a work in progress for a LiveCV plugin corresponding with the OpenCV [photo module](http://docs.opencv.org/2.4.13/modules/photo/doc/photo.html). Currently two of five methods (fastNlMeansDenoising and fastNlMeansDenoisingColored) are implemented, although the QDoc is not yet complete. Both are implemented as FastNlMeansDenoising, with a setting to use the non-color or color version. This is autodetected by default based on the number of channels, which is what you'd want unless you're doing advanced stuff with channels and color spaces, I believe.

I ran into an issue with the application hanging with 100% CPU usage when the FastNlMeansDenoising component was initialized without an input or together with the component providing its input. Turns out that the underlying OpenCV functions choke on the empty Mat that the transform() function is fed before there is any real input. Maybe you already knew this but if not, it's good to keep in mind that not all OpenCV functions can handle an empty matrix input.

### CODE REVIEW

**Comment by tvdstaaij** [comment]
Also implemented FastNlMeansDenoisingMulti (both noncolor and color), and added the relevant documentation and a sample.

The only remaining algorithm in 2.4 is inpaint, which I don't find it worth writing a wrapper for. After LiveCV switches to OpenCV3 there will be more algorithms to implement in this plugin.

So this plugin is ready for review and/or merge.

**Comment by dinusv** [comment]
I didnt know about the empty matrix issue, but yet I haven't explored much of the photo module from open cv. I'll have a look tomorrow and do the merge. 

I have to check inpaintings capabilities, seems similar to the clone tool in photoshop/gimp. it might work as a brush.

Thanks again for your input!

**Comment by tvdstaaij** [comment]
The idea of the buffer (which does hold a user-controllable number of matrices) was to allow piping a streaming input directly to the filter, which is a suggestion in the OpenCV documentation and my personal use case for the Multi (although it turns out to be horribly slow for live video processing, only barely usable with tuned down settings with my hardware). If I understand your suggestion correctly it would make other potential use cases (such as denoising multiple static photos of the same scene) easier but video processing harder. In that case it would basically be a tradeoff between usage scenarios.

These classes are also compatible with OpenCV3 by the way. On an unrelated note, the background subtraction classes I submitted earlier are not, because of API incompatible changes. I am currently redoing some of that because the project I am using LiveCV for is migrating to OpenCV3, and I switched to OpenCV3 in my personal LiveCV fork. So if/when you migrate LiveCV to OpenCV3, I probably have updated background subtraction wrappers available.

**Comment by dinusv** [comment]
Ah, I didn't notice the TemporalWindow property's function. It is kind of slow, maybe a gpu version would be faster but I haven't seen one implemented. 

Yea, it kind of boils down to each use case, the tradeoff for worst case scenario [Videos on a list based and images on a buffer based] is more in user readability, since both scenarios seem easier to write in your version:

```
// MatList based
VideoCapture{ id: videoCapture; ... }
MatBufferQueue{
  id: queue
  limit: 3 // total stored matrixes
  input: videoCapture.output
}
FastNlMeansDenoisingMulti{
  input : queue.output // Receives as a MatList{}
}

// Input Buffer Based
ImRead{ Component.onCompleted: denoising.input = output; }
ImRead{ Component.onCompleted: denoising.input = output; }
FastNlMeansDenoisingMulti {  
  id : denoising
}
```

Let's keep it like that then since it serves your use case and that will probably be the most frequently used one as well.

**Comment by dinusv** [comment]
I've had a few requests to switch to Open CV 3, so it's on my priority list to change it as well. I've already received some patches:

https://github.com/livecv/livecv/issues/61#issuecomment-244605473

As soon as I free up some time I will make the changes, at least for the dev branch.

**Comment by tvdstaaij** [comment]
Nearly the entire LiveCV core is already v3 compatible, the biggest problem is API incompatible changes regarding algorithm class usage, which affects plugins that use class-based algorithms. Some problems this caused for me:
* Some algorithms have been removed or moved to contrib.
* Generic get/set has been replaced by specific getter/setter methods.
* It is no longer allowed to invoke algorithm class constructors directly. You have to invoke a factory function, which does the allocation and returns an OpenCV smart pointer (`cv::Ptr`). This is especially inconvenient with the StateContainer because it expects a naked pointer. As a workaround I am using the smart pointer type as the StateContainer template type, i.e. `QStateContainer<Ptr<SomeOpenCVClass>>`. Which technically works, but it would perhaps be better to refactor the StateContainer to accept OpenCV smart pointers (possibly with overloads).

This affects lcvfeatures2d and the background subtractors I added, the other plugins are fine I think.

**Comment by dinusv** [comment]
So I made the switch to Open CV 3. Some feature detectors were removed and other parts seem to be in Open CV contrib. I'm going to include most of contrib modules in Live CV, however I would keep it as an optional for the build, so I'm thinking of adding a config flag for that.

I've currently commented out the BackgroundSubtractors, so if you happen to have the new implementations let me know.

I'll have a look and see what I can do with the state container, since smart pointers would be a separate case since they are not deletable as the rest of the objects.

**Comment by tvdstaaij** [comment]
> I've currently commented out the BackgroundSubtractors, so if you happen to have the new implementations let me know.
Sure, I'll have to clean it up a bit, I'll send a new PR when I'm done. I deleted BackgroundSubtractorMog entirely because it was among the classes moved to contrib and there isn't much reason to use it over Mog2 anyway as far as I know. Instead I added BackgroundSubtractorKnn, which is new in OpenCV3.

> I'll have a look and see what I can do with the state container, since smart pointers would be a separate case since they are not deletable as the rest of the objects.
Well, smart pointers have a reference counter that decreases when the pointer instance is deleted, and the object of interest is deleted when the reference count is zero. So I believe you can in fact just delete the smart pointer and the object of interest will be deleted as well, as long as there are no other smart pointers pointing to it (and if there are, you wouldn't want the object of interest to be deleted anyways). There is also an explicit release() method which does the same without having to destroy the smart pointer instance.

**Comment by dinusv** [comment]
It would work, I was thinking of avoiding pointers to smart pointers, but I'll probably end up doing that in the end.

**Pull request merged**
